import Navbar from '@/components/global/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Raleway, Noto_Sans_Cypriot } from 'next/font/google'

const raleway = Raleway({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
})
const archivo = Noto_Sans_Cypriot({
  weight: ['400'],
  subsets: ['cypriot'],
  display: 'swap',
  variable: '--font-archivo',
})


export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
  themeColor: '#FAFAFA'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${archivo.className} ${raleway.variable} ${archivo.variable}`}>
        <nav>
          <Navbar />
        </nav>
        <main className='mt-14 md:mt-0 md:mb-14 p-12 md:p-16'>
          {children}
        </main>
      </body>
    </html>
  )
}
