import Navbar from '@/components/global/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Raleway } from 'next/font/google'

const raleway = Raleway({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-raleway',
})

const bergen = localFont({
  src: [
    {
      path: '../fonts/BergenSans-Regular.otf',
      weight: 'normal',
    },
  ],
  variable: '--font-bergen',
})

const redtone = localFont({
  src: [
    {
      path: '../fonts/Redtone-Regular.woff2',
      weight: 'normal',
    },
  ],
  variable: '--font-redtone',
})

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1',
  themeColor: '#FAFAFA'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="snap-mandatory lg:snap-y lg:scroll-py-8">
      <body className={`${raleway.className} ${raleway.variable} ${bergen.variable} ${redtone.variable}`}>
        <nav>
          <Navbar breakpoint={1024} />
        </nav>
        <main className='pb-12 lg:py-[4.5rem] px-6 md:px-10 lg:px-16 '>
          {children}
        </main>
      </body>
    </html>
  )
}
